name: rust_book
description: Demonstrates how to use the flutter_inappwebview plugin.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 2.3.2+8

publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  path_provider: ^2.1.3
  flutter_inappwebview: ^6.0.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8
  flutter_archive: ^6.0.3
  connectivity_plus: ^6.0.3
  http: ^1.2.1
  path: ^1.9.0
  searchfield: ^1.0.1
  fluentui_system_icons: ^1.1.238
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  # integration_test: ^1.0.2+1
#  integration_test:
#    git:
#      url: https://github.com/flutter/plugins.git
#      path: packages/integration_test
  flutter_lints: ^4.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
